dbt_oracle:
  outputs:
    dev:
      host: '{{ env_var(''DBT_ORACLE_HOST'') }}'
      password: '{{ env_var(''DBT_ORACLE_PASSWORD'') }}'
      port: 1522
      protocol: tcp
      schema: '{{ env_var(''DBT_ORACLE_SCHEMA'') }}'
      service: '{{ env_var(''DBT_ORACLE_SERVICE'') }}'
      threads: 1
      type: oracle
      user: '{{ env_var(''DBT_ORACLE_USER'') }}'
  target: dev
